title: What the Flux
description: >-
  Join us on an innovative journey to reshape electric mobility! Our Campus Founders Challenge project aims to create a sustainable and economically feasible value chain for electric vehicle charging. We're collaborating with partners to help stabilize the power grid and make electric mobility more accessible and affordable for everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whattheflux.online" # the base hostname & protocol for your site
twitter_username: what_the_flux
github_username: PiotrJerzy13

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sass-converter

sass:
  sass_dir: assets/css
